# Generated by Django 4.1.7 on 2023-03-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=120, unique=True)),
                ('model', models.CharField(choices=[('7', '7'), ('8', '8'), ('11', '11'), ('12', '12'), ('13', '13'), ('X', 'X'), ('Xr', 'Xr'), ('Xsmax', 'Xsmax')], max_length=6)),
                ('category', models.CharField(choices=[('Simple', 'Simple'), ('+', '+'), ('Pro', 'Pro'), ('Promax', 'Promax')], max_length=6)),
                ('taille', models.CharField(choices=[('32', 32), ('64', 64), ('128', 128), ('256', 256), ('512', 512)], max_length=3)),
                ('stock', models.IntegerField(default=0)),
                ('price_acquisition', models.IntegerField(default=0)),
                ('date_acquisition', models.DateTimeField(blank=True, null=True)),
                ('price_marcher', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Moratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('adresse', models.CharField(max_length=120)),
                ('tel', models.CharField(max_length=120)),
                ('montant', models.IntegerField(default=0)),
                ('avance', models.IntegerField(default=0)),
                ('restant', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('iphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.iphone')),
            ],
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versement', models.IntegerField(default=0)),
                ('date_versement', models.DateTimeField(auto_now_add=True)),
                ('client_moratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.moratoire')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('adresse', models.CharField(max_length=120)),
                ('tel', models.CharField(max_length=120)),
                ('montant', models.IntegerField(default=0)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('iphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.iphone')),
            ],
        ),
    ]
